name: Playwright Tests 

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checks out your repository

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.204' # Ensures the correct .NET version is installed

      - name: Build project
        run: dotnet build  # Builds the project before running tests

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI  # Installs Playwright CLI

      - name: Install Playwright Browsers
        run: playwright install  # Installs required Playwright browsers

      - name: List available tests
        run: dotnet test --list-tests  # Lists all tests before execution

      - name: Run tests with detailed logging
        run: dotnet test --logger "console;verbosity=detailed"  # Runs tests with detailed output
